### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#106] opened 2021-04-25 09:25 UTC
Navigation buttons or a menu are missing from the toolbar:
1. public editions and private editions link should be on all pages
2. Create a copy once you are in a public edition
3. Add option to delete an addition

**Comment by Bronson-Brown-deVost** [comment] 2021-05-06 10:33
For point 1, clicking on the title "S Scripta Qumranica Electronica" does this, but it is probably not so obvious.  We might change the title "Scripta Qumranica Electronica", we will definitely change the icon "S".  Let's solve these issues at the same time?  Any suggestions?

For point 2, see #117.
For point 3, see now #125.

**Comment by zmbq** [comment] 2021-07-26 10:12
This is a duplicate of various other issues. Closing.

**Closed by zmbq** 2021-07-26 10:12 UTC
Labels: question, short turnaround time
