### ISSUE TITLE
Slide bar for zoom of artefact window

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#313] opened 2021-11-09 07:14 UTC
the number is confusing in the zoom, and it reaches a maximum and minimum which do not correlate with the number.
perhaps a slide bar (lik the adjust image) would be preferable?

**Comment by zmbq** [comment] 2021-12-09 08:04
Duplicate of #312

**Closed by zmbq** 2021-12-09 08:04 UTC
Labels: bug, layout
